require("plugins")
require("colorscheme_config")
require("functions")
require("lsp_config")
require("lualine_config")
require("settings")
require("plugins_settings")
require("mappings")
require("autocommands")
require("lightspeed_config")
vim.cmd 'source ~/.config/nvim/vimscript/functions.vim'
