#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.

# Override cd to go to the venv root
cd () {
    if (( $# == 0 ))
    then
        builtin cd $PROJECT_HOME/$PROJECT_NAME
    else
        autoenv_cd "$@"
    fi
}

cd
