# Executes commands at login post-zshrc.

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Start the dropbox daemon if it isn't running.
if [[ $+commands[dropbox] == 1 && $(dropbox status) =~ "Dropbox isn't running\!" ]]; then
    dropbox start
fi
