# Executes commands at login pre-zshrc.

# Paths
typeset -gU cdpath fpath mailpath path

# Editors
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

# Less
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS='-g -i -M -R -S -w -X -z-4'

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
  TMPPREFIX="${TMPDIR%/}/zsh"
fi

[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color
[[ -z "$LANG" ]] && export LANG='en_US.UTF-8'
