#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# 256 colors in terminal
[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color

# Require virutal environment
export PIP_REQUIRE_VIRTUALENV=true

# Caching packages
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

# Less syntax highlighting
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Configure virtualenv wrapper
PROJECT_HOME='/home/mike'
VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME
source /usr/local/bin/virtualenvwrapper.sh
