# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# FZF default variables
export FZF_DEFAULT_COMMAND='find . '
export FZF_DEFAULT_OPTS="--ansi"

# ADD XDG_CONFIG_HOME variable
export XDG_CONFIG_HOME=$HOME/.config

# Add Virtualenv to PATH
PROJECT_HOME='/home/mike/projects'
VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects

# Add Home/.zfunctions to FPATH
export FPATH=$FPATH:$HOME/.zfunctions

# Add Home/bin to PATH
export PATH=$PATH:$HOME/bin

# Add RVM to PATH for scripting
export GEM_HOME=$HOME/.gem
export PATH=$PATH:$HOME/.rvm/bin
export PATH=$PATH:$GEM_HOME/ruby/2.3.0/bin

# Add Local PIP to PATH
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
export PATH=$PATH:$HOME/.local/bin

# Add GOPATH to Path
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Add Heroku to Path
export PATH=$PATH:/usr/local/heroku/bin
