# Modeline and Notes {
# vim: set sw=4 ts=4 sts=4 et tw=79 foldmarker={,} foldlevel=0 foldmethod=marker spell:
# }


# Source Prezto {
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# }


# Source Aliases {
[ -f ~/.zaliases ] && source ~/.zaliases
# }


# Source Fuzzyfinder {
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# }

# Source K {
[ -f ~/.k.zsh/k.sh ] && source ~/.k.zsh/k.sh
# }


# Source Auto Env {
source ~/.autoenv/activate.sh
# }


# Auotload Custom Functions {
# fpath=(~HOME/.zfunctions $fpath)
# autoload -U compaudit compinit

source ~/.zfunctions/

source ~/.zplug/init.zsh

zplug "zplug/zplug"
zgen "djui/alias-tips"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
# }
