#!/usr/bin/fish

complete -c todo -s @ --description "Hide context names in list output"
complete -c todo -s + --description "Hide project names in list output"
complete -c todo -o @@ --description "Show context names in list output"
complete -c todo -o ++ --description "Show project names in list output"
complete -c todo -s c --description "Color mode"
complete -c todo -s D --description "Alternate configuration file"
complete -c todo -s f --description "Force actions without confirmation"
complete -c todo -s p --description "Plain mode, disable colors"
complete -c todo -s P --description "Disable priority labels"
complete -c todo -s a --description "Auto archive done tasks"
complete -c todo -s n --description "Preserve line numbers"
complete -c todo -s N --description "Don't preserve line numbers"
complete -c todo -s t --description "Prepend current date when adding task"
complete -c todo -s T --description "Don't prepend current date when adding task"
complete -c todo -s v --description "Verbose mode"
complete -c todo -s vv --description "Extra verbose mode"
complete -c todo -s x --description "Disable TODOTXT_FINAL_FILTER"

complete -c todo -a add -r --description "Adds task"
complete -c todo -a a -r --description "Adds task"
complete -c todo -a addm -r --description "Adds multiple tasks"
complete -c todo -a addto -r --description "Adds line to a file in todo.tx directory"
complete -c todo -a append -r --description "Appends text to a task"
complete -c todo -a app -r --description "Appends text to a task"
complete -c todo -a archive -r --description "Moves all done tasks done.txt"
complete -c todo -a deduplicate -r --description "Removes duplicate tasks"
complete -c todo -a del -r --description "Deletes a task"
complete -c todo -a rm -r --description "Deletes a task"
complete -c todo -a depri -r --description "Removes priority of a task"
complete -c todo -a dp -r --description "Removes priority of a task"
complete -c todo -a do -r --description "Markes a task as done"
complete -c todo -a help -r --description "Prints help"
complete -c todo -a ls -r --description "Lists tasks"
complete -c todo -a list -r --description "Lists tasks"
complete -c todo -a lsa -r --description "Lists tasks"
complete -c todo -a listall -r --description "Lists tasks including done tasks"
complete -c todo -a listaddons -r --description "Lists addons"
complete -c todo -a listcon -r --description "Lists contexts"
complete -c todo -a lsc -r --description "Lists contexts"
complete -c todo -a listsproj -r --description "Lists projects"
complete -c todo -a lsprj -r --description "Lists projects"
complete -c todo -a listpri -r --description "Lists tasks with priority"
complete -c todo -a lsp -r --description "Lists tasks with priority"
complete -c todo -a move -r --description "Moves task between files"
complete -c todo -a prepend -r --description "Prepends text to a task"
complete -c todo -a prep -r --description "Prepends text to a task"
complete -c todo -a pri -r --description "Sets priority to a task"
complete -c todo -a p -r --description "Sets priority to a task"
complete -c todo -a replace -r --description "Replaces task with new one"
complete -c todo -a report -r --description "Reports to report.txt"

complete -c todo -r -f
# complete -c todo --description "Context" -a "(todo.sh listcon)"
# complete -c todo --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
# complete -c todo --description "Project" -a "(todo.sh listproj)"
# complete -c todo --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c todols -r -f
# complete -c todols --description "Context" -a "(todo.sh listcon)"
# complete -c todols --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
# complete -c todols --description "Project" -a "(todo.sh listproj)"
# complete -c todols --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c todol -r -f
# complete -c todol --description "Context" -a "(todo.sh listcon)"
# complete -c todol --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
# complete -c todol --description "Project" -a "(todo.sh listproj)"
# complete -c todol --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c todoa -r -f
# complete -c todoa --description "Context" -a "(todo.sh listcon)"
# complete -c todoa --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
# complete -c todoa --description "Project" -a "(todo.sh listproj)"
# complete -c todoa --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"
